name: todo_list_app
description: "A simple to-do list app"
version: 1.0.0

publish_to: 'none' 

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.0
  flutter_localizations:
    sdk: flutter
 
  cupertino_icons: ^1.0.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/l10n/

  localization:
    path: lib/l10n
    arb-dir: lib/l10n
    output-dir: lib/l10n
    template-arb-file: lib/l10n/en.arb